<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HitosHistoricosSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('hitos_historicos')->insert([
            [
                'anio' => '1995',
                'fecha_texto' => '20 de enero',
                'titulo' => 'Creación oficial',
                'descripcion' => 'La Institución Educativa “Crl. José Joaquín Inclán” fue creada mediante Resolución Directoral N.° 021, con la finalidad de brindar educación a los hijos del personal militar y civil del Ejército, así como a estudiantes de la comunidad piurana.',
                'icono' => 'documento',
                'imagen' => null,
                'orden' => 1,
                'estado' => true,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'anio' => '1995',
                'fecha_texto' => '5 de mayo',
                'titulo' => 'Inicio de labores académicas',
                'descripcion' => 'La institución inició sus actividades con 130 estudiantes, siete docentes y bajo la dirección del Crl. José Beltrán Lora. En sus primeros años atendió los niveles de primaria y secundaria en los turnos mañana y tarde.',
                'icono' => 'estudiantes',
                'imagen' => null,
                'orden' => 2,
                'estado' => true,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'anio' => '1996',
                'fecha_texto' => null,
                'titulo' => 'Incorporación del nivel inicial',
                'descripcion' => 'Se amplió el servicio educativo con la atención del nivel inicial, comenzando con aulas prefabricadas para estudiantes de cuatro y cinco años.',
                'icono' => 'escuela',
                'imagen' => null,
                'orden' => 3,
                'estado' => true,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'anio' => '1997',
                'fecha_texto' => null,
                'titulo' => 'Primeras grandes ampliaciones',
                'descripcion' => 'Se construyeron cuatro aulas de material noble para inicial, tres aulas para secundaria, una plataforma deportiva y el busto del coronel José Joaquín Inclán.',
                'icono' => 'construccion',
                'imagen' => null,
                'orden' => 4,
                'estado' => true,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'anio' => '1998',
                'fecha_texto' => null,
                'titulo' => 'Secundaria completa',
                'descripcion' => 'Debido a la creciente demanda se cerró el turno de tarde y se amplió la atención secundaria hasta quinto año. También se construyeron nuevas aulas, una escalera, servicios higiénicos y el laboratorio de Física y Química.',
                'icono' => 'laboratorio',
                'imagen' => null,
                'orden' => 5,
                'estado' => true,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'anio' => '1999',
                'fecha_texto' => null,
                'titulo' => 'Nuevos espacios institucionales',
                'descripcion' => 'Se construyeron tres aulas en el segundo piso del nivel secundario y oficinas prefabricadas destinadas a las coordinaciones académicas.',
                'icono' => 'oficinas',
                'imagen' => null,
                'orden' => 6,
                'estado' => true,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'anio' => '2000–2004',
                'fecha_texto' => null,
                'titulo' => 'Mejoramiento de los ambientes',
                'descripcion' => 'Con apoyo de Foncodes se construyeron aulas y servicios higiénicos para primaria. Posteriormente se implementaron techos para los patios de secundaria y primaria, así como el estrado institucional.',
                'icono' => 'infraestructura',
                'imagen' => null,
                'orden' => 7,
                'estado' => true,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'anio' => '2010–2015',
                'fecha_texto' => null,
                'titulo' => 'Modernización integral',
                'descripcion' => 'Se remodelaron baños, aulas, oficinas y el laboratorio. Además, se construyeron nuevas aulas, canchas sintéticas, almacenes, una cocina para Qali Warma y un aula de innovación tecnológica.',
                'icono' => 'modernizacion',
                'imagen' => null,
                'orden' => 8,
                'estado' => true,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'anio' => '2013',
                'fecha_texto' => '21 de noviembre',
                'titulo' => 'Primera aula Smart School del Perú',
                'descripcion' => 'Se inauguró un aula inteligente equipada con herramientas tecnológicas interactivas, mediante un convenio con Samsung, empresarios de la educación y el Gobierno Regional de Piura.',
                'icono' => 'tecnologia',
                'imagen' => null,
                'orden' => 9,
                'estado' => true,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'anio' => 'Actualidad',
                'fecha_texto' => null,
                'titulo' => 'Una institución en constante crecimiento',
                'descripcion' => 'La institución atiende los niveles inicial, primaria y secundaria, cuenta con docentes permanentemente capacitados y continúa fortaleciendo su infraestructura y propuesta educativa.',
                'icono' => 'actualidad',
                'imagen' => null,
                'orden' => 10,
                'estado' => true,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}